basePath: /
definitions:
  main.shortTask:
    properties:
      complete:
        type: boolean
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a todo-list server.
  title: Gin Swagger todo-list API
  version: "1.0"
paths:
  /tasks:
    delete:
      consumes:
      - '*/*'
      description: Deletes all tasks
      produces:
      - application/json
      responses: {}
      summary: deleteTasks
      tags:
      - root
    post:
      consumes:
      - '*/*'
      description: Adds new task at the end of database
      parameters:
      - description: Task to add
        in: body
        name: Task
        required: true
        schema:
          $ref: '#/definitions/main.shortTask'
      produces:
      - application/json
      responses: {}
      summary: postTasks
      tags:
      - root
  /tasks/{id}:
    get:
      consumes:
      - '*/*'
      description: Gets all tasks with specified ID
      parameters:
      - description: ID to get
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: getTaskByID
      tags:
      - root
schemes:
- http
swagger: "2.0"
