basePath: /
definitions:
  main.TaskPayload:
    properties:
      complete:
        type: boolean
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a todo-list server.
  title: Gin Swagger todo-list API
  version: "1.0"
paths:
  /tasks:
    delete:
      consumes:
      - '*/*'
      description: Deletes all tasks
      produces:
      - application/json
      responses: {}
      summary: deleteTasks
    get:
      consumes:
      - '*/*'
      description: Gets all tasks in database
      produces:
      - application/json
      responses: {}
      summary: getTasks
      tags:
      - root
    post:
      consumes:
      - '*/*'
      description: Adds new task at the end of database
      parameters:
      - description: Task to add
        in: body
        name: Task
        required: true
        schema:
          $ref: '#/definitions/main.TaskPayload'
      produces:
      - application/json
      responses: {}
      summary: postTasks
      tags:
      - root
  /tasks/complete/{complete}:
    get:
      consumes:
      - '*/*'
      description: Gets all tasks with specified "complete" value
      parameters:
      - description: Complete? true or false
        in: path
        name: complete
        required: true
        type: boolean
      produces:
      - application/json
      responses: {}
      summary: getTasksByComplete
      tags:
      - root
  /tasks/id/{id}:
    delete:
      consumes:
      - '*/*'
      description: Deletes tast at specified ID
      parameters:
      - description: The specified ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: deleteTaskByID
      tags:
      - root
    get:
      consumes:
      - '*/*'
      description: Gets all tasks with specified ID
      parameters:
      - description: ID to get
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: getTaskByID
      tags:
      - root
schemes:
- http
swagger: "2.0"
