basePath: /
definitions:
  main.Task:
    properties:
      complete:
        type: boolean
      id:
        type: integer
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a todo-list server.
  title: Gin Swagger todo-list API
  version: "1.0"
paths:
  /tasks:
    post:
      consumes:
      - '*/*'
      description: Adds new task at the end of database
      parameters:
      - description: The task to add
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/main.Task'
      produces:
      - application/json
      responses: {}
      summary: postTasks
      tags:
      - root
schemes:
- http
swagger: "2.0"
