basePath: /
definitions:
  main.TaskPayload:
    properties:
      complete:
        type: boolean
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a todo-list server.
  title: Gin Swagger todo-list API
  version: "1.0"
paths:
  /tasks:
    delete:
      consumes:
      - '*/*'
      description: Deletes all tasks
      produces:
      - application/json
      responses: {}
      summary: deleteTasks
      tags:
      - tasks
    get:
      consumes:
      - '*/*'
      description: Gets all tasks in database that pass applied filter
      parameters:
      - description: id
        in: query
        name: id
        type: integer
      - description: title
        in: query
        name: title
        type: string
      - description: complete
        in: query
        name: complete
        type: boolean
      produces:
      - application/json
      responses: {}
      summary: getTasksByFilter
      tags:
      - tasks
    post:
      consumes:
      - '*/*'
      description: Adds new task at the end of database
      parameters:
      - description: Task to add
        in: body
        name: Task
        required: true
        schema:
          $ref: '#/definitions/main.TaskPayload'
      produces:
      - application/json
      responses: {}
      summary: postTasks
      tags:
      - tasks
  /tasks/id/{id}:
    delete:
      consumes:
      - '*/*'
      description: Deletes tast at specified ID
      parameters:
      - description: The specified ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: deleteTaskByID
      tags:
      - tasks
    patch:
      consumes:
      - '*/*'
      description: Toggles complete at specified ID
      parameters:
      - description: The specified ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: patchCompleteByID
      tags:
      - tasks
schemes:
- http
swagger: "2.0"
