basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a todo-list server.
  title: Gin Swagger todo-list API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get all tasks.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the tasks.
      tags:
      - root
schemes:
- http
swagger: "2.0"
